version: '3'

services:
  app:
    build:
      context: .
    environment:
      APP_URL: http://localhost:${DEV_PORT:-8080}
      PORT: 8080
    ports:
      - ${DEV_PORT:-8080}:8080
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
